### ISSUE TITLE
Alternative potentiometer

### ISSUE THREAD

**Issue by zbowden** [ToyotaInfoTech/RAMN#23]
I'm having trouble finding the potentiometer specified. Do you have any suggestions for an alternative to (or place you have sourced) the potentiometer:
Ref Des - RV3
Manufacturer - Alps Alpine
Part Number - RK09D1110C0R

Thanks!

**Comment by CamilleTTT** [comment]
Hello!

Indeed, RK09D1110C0R (25mm shaft) appears to be EOL.
Following potentiometers have the same footprint and are currently available on Mouser:
RK09K1110B26 (20mm shaft, linear taper)
RK09K1110A2S (15mm shaft, logarithmic taper) 
(Firmware is available for both linear and logarithmic tapers)

We made some PCBs with RK09K1110A2S, due to the shorter shaft the knob tends to fall off more easily but they are perfectly usable.

**Comment by zbowden** [comment]
Perfect, thank you. Closing this issue.
